migueldeicaza/SwiftTerm

SwiftTerm/Sources/SwiftTerm/Mac/MacCaretView.swift, SwiftTerm/Sources/SwiftTerm/Mac/MacSelectionView.swift, SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift
Use system-defined colors for text/background/caret - this makes it work nicely in light/dark mode
=> Use system colors (dark/light mode compatible)

.gitignore, SwiftTerm.xcodeproj/project.pbxproj, SwiftTerm/Sources/SwiftTerm/Buffer.swift, SwiftTerm/Sources/SwiftTerm/CircularList.swift, SwiftTerm/Sources/SwiftTerm/Mac/MacSelectionView.swift, SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift, SwiftTerm/Sources/SwiftTerm/Mac/TerminalViewDelegate.swift, SwiftTerm/Sources/SwiftTerm/TerminalOptions.swift
Fixes #54 
In this PR:
- Selection highlight in pair with displayed glyphs
- before
- after
- dynamic line-height support
- before
- after
- Improved support for font metrics. Calculate lines positions based on used font (no more magic offset values)
- Sharp background frame - `fullBackgroundColor` attribute
- before
- after
=> Mac: Improve fonts metrics and line drawing

SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift
- Use `NSView.autoresizingMask` to layout and forget for subviews. Scroller and SelectionView
- Use bounds for subviews instead of frame.
=> Use layout system to layout subviews. Subviews use bounds.

SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/EventHandlingBasics/EventHandlingBasics.html
> If your implementation of an NSResponder method such as mouseDown: completely handles an event it **should not invoke the superclass** implementation of that method.
=> Don't invoke the superclass of mouse responder methods

SwiftTerm/Sources/SwiftTerm/Terminal.swift
I was running with memory bounds checks and found this
=> add terminator to byte array that is read a null terminated c string

SwiftTerm/Sources/SwiftTerm/CharData.swift, SwiftTerm/Sources/SwiftTerm/Terminal.swift
A few changes to allow using the Terminal object from outside the SwiftTerm module.
You can read the following:
* CharData for a given row and column
* whether terminal is in application cursor mode or not
* cursor location relative to visible screen
* top visible row to help handle scrolling
=> Expose Terminal information outside module

Sources/SwiftTerm/Apple/AppleTerminalView.swift
Reproducer:
```sh
$ printf "\033[1;38;5;251mCRASH\033[0m\n"
```
=> Fix an index out of bounds crash when using ansi256 color + bold

Sources/SwiftTerm/Apple/AppleTerminalView.swift, Sources/SwiftTerm/BufferLine.swift, Sources/SwiftTerm/EscapeSequenceParser.swift, Sources/SwiftTerm/Mac/MacTerminalView.swift, Sources/SwiftTerm/SixelDcsHandler.swift, Sources/SwiftTerm/Terminal.swift, Sources/SwiftTerm/iOS/iOSTerminalView.swift, TerminalApp/iOSTerminal.xcodeproj/project.xcworkspace/contents.xcworkspacedata, TerminalApp/iOSTerminal/UIKitSshTerminalView.swift, TerminalApp/iOSTerminal/ViewController.swift
This implements a more responsive terminal in particular in scenarios where
a lot of data might be delivered by a remote end-point, or where the remote data
has been queued.
This work was first proposed and documented here:
https://github.com/migueldeicaza/SwiftTerm/issues/137
I originally thought that what I should do was to make the parsing take place in
a background thread, and keep the UI updating using a `CADisplayLink` to ensure
smooth updates.   While did this work, it made the code more complicated in places
where it did not have to be - in particular, events were being raised on a background 
thread.   There was also an additional problem, which I documented like this
on the issue:
```
Observation on multi-threading: while this works fabulously, the current system will 
just take …
```
=> Better background processing

Sources/SwiftTerm/Terminal.swift
`selectCharset()` could overflow when called with incorrect parameters.
`if CharSets.all.keys.contains(p [1]){` a few lines down fails if `count < 2` and by returning early this can no longer happen.
=> avoid buffer overflow in selectCharset

Sources/SwiftTerm/Apple/AppleTerminalView.swift
There is no need to draw the cursor in the draw method, as it is draw…
cc3ddc5
…n later by `updateDisplay(...)`.
This is removed because of some crash when a terminal is used inside of a SwiftUI `VSplitView` (maybe also others)
When the `updateCursorPostion` method is called in the drawDirtyRect method, it causes a crash at `addSubview(caretView)` in line 628. The message is:
"The window has been marked as needing another Update Constraints in Window pass, but it has already had more Update Constraints in Window passes than there are views in the window"
=> Issue with `updateCursorPostion` in drawDirtyRect

Sources/SwiftTerm/Apple/AppleTerminalView.swift
Stretch last col/row to fill the view frame.
Problem: If the view frame is not exactly the size of the grid, the background does not cover the whole frame - that looks like here:
https://user-images.githubusercontent.com/758033/105563386-2a98ef80-5d1e-11eb-8dd0-ed37ff5e7004.mov
=> Stretch last col/row to fill the view frame

Sources/SwiftTerm/iOS/iOSTextInput.swift
Fix issue on macOS when a position is not defined on the compare( ) method
=> Add check for position when one of them is not defined 

Sources/SwiftTerm/Mac/MacLocalTerminalView.swift
NSPasteboard.general() not worked on swift 5 whitch need to be modify into NSPasteboard.general.
=> fix NSPasteboard.general

Sources/SwiftTerm/iOS/iOSTerminalView.swift
expose a call to invalidate CADisplayLink in order to prevent retain of TerminalView
=> CADisplayLink  retain TerminalView fix

Sources/SwiftTerm/iOS/iOSTerminalView.swift
This allows showing shortcut keys all the time, along the patch on LaTerminalApp this will work
=> remove extra empty row, show input accessory for hardware keyboard

Sources/SwiftTerm/Apple/AppleTerminalView.swift, Sources/SwiftTerm/Apple/CaretView.swift, Sources/SwiftTerm/Mac/MacCaretView.swift, Sources/SwiftTerm/Mac/MacTerminalView.swift, Sources/SwiftTerm/Terminal.swift, Sources/SwiftTerm/iOS/iOSCaretView.swift, Sources/SwiftTerm/iOS/iOSTerminalView.swift, TerminalApp/MacTerminal/ViewController.swift, TerminalApp/iOSTerminal/ViewController.swift
This solves a long-standing problem where block cursors hid the text underneath, a problem
that had been sort of masked with blinking, colors or underline/bar cursors, but they always 
bothered me.
Now we will respect the cursor background color, and allows themes to set the text color
when the cursor is highlighted - if not set, it defaults to the foreground color for the text.
=> The caret will now render the character underneath it.

Sources/SwiftTerm/LocalProcess.swift
If a LocalProcess is terminated or exits right before the hosting LocalProcessTerminalView is released, the processTerminated call crashes the app with the following error:
```
Fatal error: Attempted to read an unowned reference but the object was already deallocated
```
All usages of delegate already have nil checks, so just change the variable from unowned to weak to fix the issue. There's no point in calling the delegate when it no longer exists.
=> Use weak ref to fix crash when process exits after view is released

Sources/SwiftTerm/iOS/iOSTerminalView.swift
`inputAccessoryView` and `inputAssistantItem` are not available.
Fixes #327
=> Fix visionOS build on latest beta SDK

Sources/SwiftTerm/Mac/MacTerminalView.swift
Fixes problem when you can subclass MacTerminalView and can subclass Terminal, but you can not initialize your "CustomMacTerminalView" with "CustomTerminal"
=> Made terminal variable public, so custom implementation can be used

Sources/SwiftTerm/Apple/AppleTerminalView.swift, Sources/SwiftTerm/Mac/MacTerminalView.swift, Sources/SwiftTerm/iOS/iOSTerminalView.swift
We can toggle weather terminal should use bright colors, so it will either use bright colors instead of bold fonts or if they are turned off it will use bold fonts instead of bright colors
=> Update logic to support new bright color flag

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, Sources/SwiftTerm/Mac/MacTerminalView.swift
View clipping needs to be set explicitly in App/UIKit on Sonoma, see here: https://indiestack.com/2023/06/view-clipping-sonoma/
This PR just adds the flag to `TerminalView`'s `setup` function.
=> Fix for TerminalView growing out of bounds in Sonoma (#330)

Sources/SwiftTerm/Apple/AppleTerminalView.swift
Uses the "W" hack for finding the cell width on macOS, similar to how it already works on iOS. Adds a commented version that comes with a performance hit as discussed in #286.
=> Use W Hack For macOS Cell Width

Sources/SwiftTerm/Apple/CaretView.swift, Sources/SwiftTerm/Mac/MacCaretView.swift
Updates the caret drawing function to clip to it's bounds. Fixes a small visual bug where the unfocused box stuck around in the layer because it was never cleared due to it being outside the view's bounds. Fixes by first clearing the entire layer and then drawing.
Updates the macOS Caret background color when the color is set using the public variable. Fixes an issue where the caret color was not being used on macOS if it was changed after initialization.
**Screenshots**
Caret drawing is mostly the same, just that it's only drawing inside the bounds of the cell the cursor is in.
Caret drawing without patch, note leftover stroke artifacts from the unfocused box when focused:
Caret drawing with patch:
macOS from CodeEdit
Focused, block
Focused, underline
Focused, bar
Unfocused
iOS from …
=> Fix Caret Drawing Artifacts

Sources/SwiftTerm/BufferLine.swift
Improved performance for terminal will large scrollback values (over 10000 lines), so memory will not be allocated for buffers that are not used
- Implemented optimisation for BufferLine, so data array will not be allocated until it is needed
- modified resize method to be more efficient if data are not allocated yet
Problem background:
During initialization and window resize Terminal will call resize method for each buffer line during which triggers memory reallocation of BufferLine.data. This operation becomes bottleneck with terminal scrollback > 10000.
Implemented fix takes into account that most of the buffers will contains only blank charactes (until something useful will be printed into it) and can be lazy allocated using known fillCharacter and expectedDataSize. In this case …
=> Improved performance with large scrollback

Sources/SwiftTerm/Mac/MacTerminalView.swift
NSScroller does not resize automatically (in height) after the initial frame setup.
Re-setup scroller on resize. Unfortunately, simply updating NSScroller.frame.height does not work as expected.
=> re-setup scroller on size change

Sources/SwiftTerm/Apple/AppleTerminalView.swift
On resize in iOS, terminal would clear which is a problem. Replaced hard reset with soft reset as suggested in https://github.com/migueldeicaza/SwiftTerm/discussions/366
=> Fix terminal clear on resize

Sources/SwiftTerm/LocalProcess.swift, Sources/SwiftTerm/Pty.swift
Allows specifying a custom currentDirectory when launching a process. Modifies PseudoTerminalHelpers.fork to accept an optional working directory parameter and calls chdir() before execve().
LocalProcess.startProcess() now propagates this new parameter.
=> Add support for setting child process working directory in LocalProcess

Sources/SwiftTerm/Mac/MacTerminalView.swift, Tests/SwiftTermTests/SelectionTests.swift
Fixes a bug where selecting text when the terminal was scrolled would select the text as if the terminal was not scrolled.
Before: 
https://github.com/user-attachments/assets/7446776b-fbe2-4176-a756-09c1fadf2dad
With changes:
https://github.com/user-attachments/assets/fe38189b-0a19-4c0e-a46d-b22666090832
=> Consider Buffer Y Offset In Mouse Hit

Sources/SwiftTerm/Mac/MacTerminalView.swift
Fixes a layout exception due to the removal of the scroller during constraint layout. This happened when the view was embedded in a SwiftUI view and SwiftUI attempted to update its frame, which caused the scroller to be removed from the view hierarchy which is illegal.
To fix I just removed the removal of the old scroller and updated its frame if it's not `nil`. This avoids a view tree update and still updates the scroller's position and size.
=> Update Scroller When Exists - Fix Layout Exception

Sources/SwiftTerm/SelectionService.swift
The selection service's start/end positions can be reversed (usually when dragging backwards in the text). This orders the start/end positions before calling `terminal.getText`.
=> Fix Selected Text

Sources/SwiftTerm/Mac/MacTerminalView.swift
The display offset is incorrectly added to selection range, if the buffer line is larger than actual display height (display offset large than 0), the row selected is the actual row plus display offset.
Stop adding the offset, so the row selected is the row mouse pointed at.
=> fix wrong selection range in scroll mode

Sources/SwiftTerm/LocalProcess.swift
Build was failing on LocalProcess L495 with `Cannot convert value of type '[String : String]' to expected argument type '[Environment.Key : String]'`
=> Fix a build issue on LocalProcess with Environment
